In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [2]:
from hcplot import loadLibraries, Figure
from hcplot.config import mapping, single, grid, matrix, wrap, scale
from hcplot.geoms import Line, Points
from hcplot.scales import Brewer, Alpha, D3, Shape, Size

loadLibraries()


- Highsoft software products (www.highcharts.com) are not free for commercial and Governmental use.
  (see https://shop.highsoft.com/faq#Non-Commercial-0 for conditions for Non-commercial use).
- This product includes color specifications and designs developed by Cynthia Brewer
  http://colorbrewer.org
- D3 category colors and the interpolateRGB algorithm have been taken over from https://d3js.org/,
  Copyright 2010-2017 Mike Bostock



<IPython.core.display.Javascript object>

In [3]:
from ggplot import mpg, mtcars, diamonds

In [3]:
%%sh 
cd /tmp
wget -q https://raw.githubusercontent.com/pandas-dev/pandas/master/pandas/tests/data/iris.csv

In [4]:
import pandas as pd
iris = pd.read_csv('/tmp/iris.csv')

In [11]:
fig = Figure(mpg, 
             mapping(x="hwy", y="displ", color="class", size="cty", alpha="drv"),
             scale(color=Brewer("qual", "Dark2", discrete=True), 
                   size=Size(end=15, discrete=False)),
             width=512, ratio=1) \
    + Points(size=5)
fig

<hcplot.scales.scale.Brewer object at 0x1068d9828> ['27,158,119', '217,95,2', '117,112,179', '231,41,138', '102,166,30', '230,171,2', '166,118,29']
<hcplot.scales.scale.Alpha object at 0x1068d90f0> [ 0.1   0.55  1.  ]


/opt/miniconda/envs/py3/lib/python3.5/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, _DataConversionWarning)


In [11]:
fig = Figure(mpg, 
             mapping(x="hwy", y="displ", color="class"),
             scale(color=Brewer("qual", "Dark2", True)),
             width=512, ratio=1) \
    + Points(size=5)
fig

In [ ]:
fig.layers[0].data.df

# BASE

# LAYER

# LINE

# FIGURE

# COLOR

# SCALE

# UTILS

# DATA

# TEMPLATES

In [4]:
from hcplot.utils.color import rgbSpline, rgb2str
from sklearn.preprocessing import MinMaxScaler


class ColorBrewer(object):
    """
    Source: http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3

    """
    divScheme = {
        "Spectral": [None, None, None,
            [(252,141, 89), (255,255,191), (153,213,148)],                                                                                                                                           # noqa E501,E231,E201
            [(215, 25, 28), (253,174, 97), (171,221,164), ( 43,131,186)],                                                                                                                            # noqa E501,E231,E201
            [(215, 25, 28), (253,174, 97), (255,255,191), (171,221,164), ( 43,131,186)],                                                                                                             # noqa E501,E231,E201
            [(213, 62, 79), (252,141, 89), (254,224,139), (230,245,152), (153,213,148), ( 50,136,189)],                                                                                              # noqa E501,E231,E201
            [(213, 62, 79), (252,141, 89), (254,224,139), (255,255,191), (230,245,152), (153,213,148), ( 50,136,189)],                                                                               # noqa E501,E231,E201
            [(213, 62, 79), (244,109, 67), (253,174, 97), (254,224,139), (230,245,152), (171,221,164), (102,194,165), ( 50,136,189)],                                                                # noqa E501,E231,E201
            [(213, 62, 79), (244,109, 67), (253,174, 97), (254,224,139), (255,255,191), (230,245,152), (171,221,164), (102,194,165), ( 50,136,189)],                                                 # noqa E501,E231,E201
            [(158,  1, 66), (213, 62, 79), (244,109, 67), (253,174, 97), (254,224,139), (230,245,152), (171,221,164), (102,194,165), ( 50,136,189), ( 94, 79,162)],                                  # noqa E501,E231,E201
            [(158,  1, 66), (213, 62, 79), (244,109, 67), (253,174, 97), (254,224,139), (255,255,191), (230,245,152), (171,221,164), (102,194,165), ( 50,136,189), ( 94, 79,162)]                    # noqa E501,E231,E201
        ],
        "RdYlGn": [None, None, None,
            [(252,141, 89), (255,255,191), (145,207, 96)],                                                                                                                                           # noqa E501,E231,E201
            [(215, 25, 28), (253,174, 97), (166,217,106), ( 26,150, 65)],                                                                                                                            # noqa E501,E231,E201
            [(215, 25, 28), (253,174, 97), (255,255,191), (166,217,106), ( 26,150, 65)],                                                                                                             # noqa E501,E231,E201
            [(215, 48, 39), (252,141, 89), (254,224,139), (217,239,139), (145,207, 96), ( 26,152, 80)],                                                                                              # noqa E501,E231,E201
            [(215, 48, 39), (252,141, 89), (254,224,139), (255,255,191), (217,239,139), (145,207, 96), ( 26,152, 80)],                                                                               # noqa E501,E231,E201
            [(215, 48, 39), (244,109, 67), (253,174, 97), (254,224,139), (217,239,139), (166,217,106), (102,189, 99), ( 26,152, 80)],                                                                # noqa E501,E231,E201
            [(215, 48, 39), (244,109, 67), (253,174, 97), (254,224,139), (255,255,191), (217,239,139), (166,217,106), (102,189, 99), ( 26,152, 80)],                                                 # noqa E501,E231,E201
            [(165,  0, 38), (215, 48, 39), (244,109, 67), (253,174, 97), (254,224,139), (217,239,139), (166,217,106), (102,189, 99), ( 26,152, 80), (  0,104, 55)],                                  # noqa E501,E231,E201
            [(165,  0, 38), (215, 48, 39), (244,109, 67), (253,174, 97), (254,224,139), (255,255,191), (217,239,139), (166,217,106), (102,189, 99), ( 26,152, 80), (  0,104, 55)]                    # noqa E501,E231,E201
        ]
    }

    qualScheme = {
        "Accent": [None, None, None,
            [(127,201,127), (190,174,212), (253,192,134)],                                                                                                                                           # noqa E501,E231,E201
            [(127,201,127), (190,174,212), (253,192,134), (255,255,153)],                                                                                                                            # noqa E501,E231,E201
            [(127,201,127), (190,174,212), (253,192,134), (255,255,153), ( 56,108,176)],                                                                                                             # noqa E501,E231,E201
            [(127,201,127), (190,174,212), (253,192,134), (255,255,153), ( 56,108,176), (240,  2,127)],                                                                                              # noqa E501,E231,E201
            [(127,201,127), (190,174,212), (253,192,134), (255,255,153), ( 56,108,176), (240,  2,127), (191, 91, 23)],                                                                               # noqa E501,E231,E201
            [(127,201,127), (190,174,212), (253,192,134), (255,255,153), ( 56,108,176), (240,  2,127), (191, 91, 23), (102,102,102)]                                                                 # noqa E501,E231,E201
         ],
        "Set1": [None, None, None,
            [(228, 26, 28), ( 55,126,184), ( 77,175, 74)],                                                                                                                                           # noqa E501,E231,E201
            [(228, 26, 28), ( 55,126,184), ( 77,175, 74), (152, 78,163)],                                                                                                                            # noqa E501,E231,E201
            [(228, 26, 28), ( 55,126,184), ( 77,175, 74), (152, 78,163), (255,127,  0)],                                                                                                             # noqa E501,E231,E201
            [(228, 26, 28), ( 55,126,184), ( 77,175, 74), (152, 78,163), (255,127,  0), (255,255, 51)],                                                                                              # noqa E501,E231,E201
            [(228, 26, 28), ( 55,126,184), ( 77,175, 74), (152, 78,163), (255,127,  0), (255,255, 51), (166, 86, 40)],                                                                               # noqa E501,E231,E201
            [(228, 26, 28), ( 55,126,184), ( 77,175, 74), (152, 78,163), (255,127,  0), (255,255, 51), (166, 86, 40), (247,129,191)],                                                                # noqa E501,E231,E201
            [(228, 26, 28), ( 55,126,184), ( 77,175, 74), (152, 78,163), (255,127,  0), (255,255, 51), (166, 86, 40), (247,129,191), (153,153,153)]                                                  # noqa E501,E231,E201
         ]
    }

    seqScheme = {
        "OrRd": [None, None, None,
            [(254,232,200), (253,187,132), (227, 74, 51)],                                                                                                                                           # noqa E501,E231,E201
            [(254,240,217), (253,204,138), (252,141, 89), (215, 48, 31)],                                                                                                                            # noqa E501,E231,E201
            [(254,240,217), (253,204,138), (252,141, 89), (227, 74, 51), (179,  0,  0)],                                                                                                             # noqa E501,E231,E201
            [(254,240,217), (253,212,158), (253,187,132), (252,141, 89), (227, 74, 51), (179,  0,  0)],                                                                                              # noqa E501,E231,E201
            [(254,240,217), (253,212,158), (253,187,132), (252,141, 89), (239,101, 72), (215, 48, 31), (153,  0,  0)],                                                                               # noqa E501,E231,E201
            [(255,247,236), (254,232,200), (253,212,158), (253,187,132), (252,141, 89), (239,101, 72), (215, 48, 31), (153,  0,  0)],                                                                # noqa E501,E231,E201
            [(255,247,236), (254,232,200), (253,212,158), (253,187,132), (252,141, 89), (239,101, 72), (215, 48, 31), (179,  0,  0), (127,  0,  0)]                                                  # noqa E501,E231,E201
         ],
        "PuBu": [None, None, None,
            [(236,231,242), (166,189,219), ( 43,140,190)],                                                                                                                                           # noqa E501,E231,E201
            [(241,238,246), (189,201,225), (116,169,207), (  5,112,176)],                                                                                                                            # noqa E501,E231,E201
            [(241,238,246), (189,201,225), (116,169,207), ( 43,140,190), (  4, 90,141)],                                                                                                             # noqa E501,E231,E201
            [(241,238,246), (208,209,230), (166,189,219), (116,169,207), ( 43,140,190), (  4, 90,141)],                                                                                              # noqa E501,E231,E201
            [(241,238,246), (208,209,230), (166,189,219), (116,169,207), ( 54,144,192), (  5,112,176), (  3, 78,123)],                                                                               # noqa E501,E231,E201
            [(255,247,251), (236,231,242), (208,209,230), (166,189,219), (116,169,207), ( 54,144,192), (  5,112,176), (  3, 78,123)],                                                                # noqa E501,E231,E201
            [(255,247,251), (236,231,242), (208,209,230), (166,189,219), (116,169,207), ( 54,144,192), (  5,112,176), (  4, 90,141), (  2, 56, 88)]                                                  # noqa E501,E231,E201
         ]
   }

    #
    # Get interpolated results for non-discrete case
    #

    @classmethod
    def _interpolate(cls, scheme, palette, series):
        colors = scheme.get(palette)[-1]
        f = rgbSpline()(colors)
        scaledSeries = MinMaxScaler([0.0, 1.0]).fit_transform(series.values.reshape(-1, 1))
        return [f(a) for a in scaledSeries]


    #
    # Get discrete results
    #

    @classmethod
    def _get(cls, scheme, palette, size):
        colors = scheme.get(palette)
        if colors is None:
            return []
        elif size is None:
            return colors
        elif size == -1:
            return colors[-1]
        elif size < 3:
            return colors[3][:size]
        elif size < len(colors):
            return colors[size]
        else:
            print("Warning: size too large for scheme, stacking largest color list to match size")
            colors = colors[-1]
            factor = math.ceil(size / (len(colors) - 3))
            return (colors * factor)[:size]

    #
    # Accessors
    #

    @classmethod
    def div(cls, palette, sizeOrSeries, asString=False):
        if isinstance(sizeOrSeries, int):
            result = cls._get(cls.divScheme, palette, size=sizeOrSeries)
        else:
            result = cls._interpolate(cls.divScheme, palette, series=sizeOrSeries)
        return rgb2str(result) if asString else result

    @classmethod
    def seq(cls, palette, sizeOrSeries, asString=False):
        if isinstance(sizeOrSeries, int):
            result = cls._get(cls.seqScheme, palette, size=sizeOrSeries)
        else:
            result = cls._interpolate(cls.seqScheme, palette, series=sizeOrSeries)
        return rgb2str(result) if asString else result

    @classmethod
    def qual(cls, palette, sizeOrSeries, asString=False):
        assert isinstance(sizeOrSeries, int), "Qualitative palette cannot be used for non-discrete data"
        result = cls._get(cls.qualScheme, palette, size=sizeOrSeries)
        return rgb2str(result) if asString else result


In [14]:
import random
import pandas as pd

data = {"X": [random.randint(-5,5) for i in range(20)],
        "Y": [random.randint(10,100) for i in range(20)]}
df = pd.DataFrame(data)

In [8]:
df["color"] = ColorBrewer.div("Spectral", df["X"], asString=True)
df.sort_values("X")

/opt/miniconda/envs/py3/lib/python3.5/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, _DataConversionWarning)


X   Y        color
9  -5  63     158,1,66
2  -5  35     158,1,66
5  -5  31     158,1,66
13 -4  91    209,59,74
11 -3  29   240,111,74
16 -2  97   251,171,99
3  -2  89   251,171,99
19 -1  74  254,220,140
6  -1  29  254,220,140
10  0  31  250,248,175
17  0  26  250,248,175
14  1  74  224,242,160
15  1  52  224,242,160
0   1  11  224,242,160
7   2  89  169,220,162
4   3  95  104,188,168
8   4  12   66,136,180
12  4  53   66,136,180
18  5  79    94,79,162
1   5  88    94,79,162

In [ ]:
df["color2"] = ColorBrewer.div("Spectral", df["X"], asString=True)
df.sort_values("X")

In [109]:
ColorBrewer.div("Spectral", df["X"], asString=True)

/opt/miniconda/envs/py3/lib/python3.5/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, _DataConversionWarning)


ValueError: setting an array element with a sequence.

In [115]:
import math
f = math.sqrt
df = pd.DataFrame({"X": [x/10.0 for x in range(2000000)]})
%timeit [f(x) for x in df["X"]]

1 loop, best of 3: 312 ms per loop


In [118]:
%timeit np.fromiter((f(xi) for xi in df["X"]), df["X"].dtype) # , count=len(df["X"]))

1 loop, best of 3: 406 ms per loop


In [11]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

In [21]:
MinMaxScaler([0.1, 1.0]).fit_transform(np.linspace(-5, 5, 20).reshape(-1,1))

array([[ 0.1       ],
       [ 0.14736842],
       [ 0.19473684],
       [ 0.24210526],
       [ 0.28947368],
       [ 0.33684211],
       [ 0.38421053],
       [ 0.43157895],
       [ 0.47894737],
       [ 0.52631579],
       [ 0.57368421],
       [ 0.62105263],
       [ 0.66842105],
       [ 0.71578947],
       [ 0.76315789],
       [ 0.81052632],
       [ 0.85789474],
       [ 0.90526316],
       [ 0.95263158],
       [ 1.        ]])

In [22]:
MinMaxScaler([0.1, 1.0]).fit_transform(df["X"].values.reshape(-1,1))

/opt/miniconda/envs/py3/lib/python3.5/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, _DataConversionWarning)


array([[ 0.9],
       [ 0.2],
       [ 0.4],
       [ 0.9],
       [ 1. ],
       [ 0.1],
       [ 0.8],
       [ 0.6],
       [ 0.4],
       [ 0.3],
       [ 0.2],
       [ 0.3],
       [ 0.8],
       [ 0.5],
       [ 0.8],
       [ 0.4],
       [ 0.2],
       [ 0.2],
       [ 0.3],
       [ 0.1]])

In [27]:
MinMaxScaler([0.1, 1.0]).fit_transform(np.array(list(range(20))).reshape(-1,1))

/opt/miniconda/envs/py3/lib/python3.5/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, _DataConversionWarning)


array([[ 0.1       ],
       [ 0.14736842],
       [ 0.19473684],
       [ 0.24210526],
       [ 0.28947368],
       [ 0.33684211],
       [ 0.38421053],
       [ 0.43157895],
       [ 0.47894737],
       [ 0.52631579],
       [ 0.57368421],
       [ 0.62105263],
       [ 0.66842105],
       [ 0.71578947],
       [ 0.76315789],
       [ 0.81052632],
       [ 0.85789474],
       [ 0.90526316],
       [ 0.95263158],
       [ 1.        ]])

In [25]:
np.array?

In [19]:
type(df["X"])

pandas.core.series.Series

In [20]:
type(np.linspace(-5, 5, 20))

numpy.ndarray

In [36]:
def c(s):
    if isinstance(s, (list, tuple)):
        return np.array(s).reshape(-1, 1)
    elif isinstance(s, np.ndarray):
        return s.reshape(-1, 1)
    elif isinstance(s, pd.core.series.Series):
        return s.values.reshape(-1, 1)

In [59]:
def linscaler(start, end, array):
    amin = min(array)
    diff = max(array) - min(array)
    return lambda x: (x - amin) / diff

In [68]:
l = 1000000
a = [i/10 for i in range(l)]
n = np.linspace(0, 1000, l)
df = pd.DataFrame({"X":np.linspace(0, 1000, l)})
d = df["X"]

In [71]:
def test1(s):
    return MinMaxScaler([0.1, 1.0]).fit_transform(c(s))

def test2(s):
    f = linscaler(0.1, 1.0, s)
    return [f(x) for x in s]

In [74]:
%timeit test1(a)
%timeit test2(a)

10 loops, best of 3: 46.9 ms per loop
1 loop, best of 3: 276 ms per loop


In [75]:
%timeit test1(s)
%timeit test2(s)

100 loops, best of 3: 9.14 ms per loop
1 loop, best of 3: 615 ms per loop


In [76]:
%timeit test1(d)
%timeit test2(d)

100 loops, best of 3: 8.91 ms per loop
1 loop, best of 3: 610 ms per loop


In [ ]:
MinMaxScaler([2, 20]).fit_transform(c(mpg["displ"])).round()

In [81]:
np.linspace(2,20, 30).round()

array([  2.,   3.,   3.,   4.,   4.,   5.,   6.,   6.,   7.,   8.,   8.,
         9.,   9.,  10.,  11.,  11.,  12.,  13.,  13.,  14.,  14.,  15.,
        16.,  16.,  17.,  18.,  18.,  19.,  19.,  20.])

In [7]:
import numpy as np

In [13]:
incr = 3
start = 3
size = 5
np.arange(start, start + incr * size, incr)

array([ 3,  6,  9, 12, 15])